//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.35312
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTest.Web.DealerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DealerInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFTest.Contract.Model")]
    [System.SerializableAttribute()]
    public partial class DealerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DealerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DealerShortNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DealerID {
            get {
                return this.DealerIDField;
            }
            set {
                if ((this.DealerIDField.Equals(value) != true)) {
                    this.DealerIDField = value;
                    this.RaisePropertyChanged("DealerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DealerShortName {
            get {
                return this.DealerShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerShortNameField, value) != true)) {
                    this.DealerShortNameField = value;
                    this.RaisePropertyChanged("DealerShortName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://price.yiche.com/", ConfigurationName="DealerService.DeslersService")]
    public interface DeslersService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://price.yiche.com/DeslersService/GetDealer", ReplyAction="http://price.yiche.com/DeslersService/GetDealerResponse")]
        WCFTest.Web.DealerService.DealerInfo GetDealer(int vendorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://price.yiche.com/DeslersService/GetDealer", ReplyAction="http://price.yiche.com/DeslersService/GetDealerResponse")]
        System.Threading.Tasks.Task<WCFTest.Web.DealerService.DealerInfo> GetDealerAsync(int vendorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://price.yiche.com/DeslersService/GetDealers", ReplyAction="http://price.yiche.com/DeslersService/GetDealersResponse")]
        WCFTest.Web.DealerService.DealerInfo[] GetDealers(int[] vendorIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://price.yiche.com/DeslersService/GetDealers", ReplyAction="http://price.yiche.com/DeslersService/GetDealersResponse")]
        System.Threading.Tasks.Task<WCFTest.Web.DealerService.DealerInfo[]> GetDealersAsync(int[] vendorIds);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeslersServiceChannel : WCFTest.Web.DealerService.DeslersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeslersServiceClient : System.ServiceModel.ClientBase<WCFTest.Web.DealerService.DeslersService>, WCFTest.Web.DealerService.DeslersService {
        
        public DeslersServiceClient() {
        }
        
        public DeslersServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeslersServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeslersServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeslersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFTest.Web.DealerService.DealerInfo GetDealer(int vendorId) {
            return base.Channel.GetDealer(vendorId);
        }
        
        public System.Threading.Tasks.Task<WCFTest.Web.DealerService.DealerInfo> GetDealerAsync(int vendorId) {
            return base.Channel.GetDealerAsync(vendorId);
        }
        
        public WCFTest.Web.DealerService.DealerInfo[] GetDealers(int[] vendorIds) {
            return base.Channel.GetDealers(vendorIds);
        }
        
        public System.Threading.Tasks.Task<WCFTest.Web.DealerService.DealerInfo[]> GetDealersAsync(int[] vendorIds) {
            return base.Channel.GetDealersAsync(vendorIds);
        }
    }
}
