//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.35312
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTest.Client.WCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://price.yiche.com/", ConfigurationName="WCFService.DeslersService")]
    public interface DeslersService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://price.yiche.com/DeslersService/GetDealer", ReplyAction="http://price.yiche.com/DeslersService/GetDealerResponse")]
        WCFTest.Contract.Model.DealerInfo GetDealer(int vendorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://price.yiche.com/DeslersService/GetDealer", ReplyAction="http://price.yiche.com/DeslersService/GetDealerResponse")]
        System.Threading.Tasks.Task<WCFTest.Contract.Model.DealerInfo> GetDealerAsync(int vendorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://price.yiche.com/DeslersService/GetDealers", ReplyAction="http://price.yiche.com/DeslersService/GetDealersResponse")]
        WCFTest.Contract.Model.DealerInfo[] GetDealers(int[] vendorIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://price.yiche.com/DeslersService/GetDealers", ReplyAction="http://price.yiche.com/DeslersService/GetDealersResponse")]
        System.Threading.Tasks.Task<WCFTest.Contract.Model.DealerInfo[]> GetDealersAsync(int[] vendorIds);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeslersServiceChannel : WCFTest.Client.WCFService.DeslersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeslersServiceClient : System.ServiceModel.ClientBase<WCFTest.Client.WCFService.DeslersService>, WCFTest.Client.WCFService.DeslersService {
        
        public DeslersServiceClient() {
        }
        
        public DeslersServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeslersServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeslersServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeslersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFTest.Contract.Model.DealerInfo GetDealer(int vendorId) {
            return base.Channel.GetDealer(vendorId);
        }
        
        public System.Threading.Tasks.Task<WCFTest.Contract.Model.DealerInfo> GetDealerAsync(int vendorId) {
            return base.Channel.GetDealerAsync(vendorId);
        }
        
        public WCFTest.Contract.Model.DealerInfo[] GetDealers(int[] vendorIds) {
            return base.Channel.GetDealers(vendorIds);
        }
        
        public System.Threading.Tasks.Task<WCFTest.Contract.Model.DealerInfo[]> GetDealersAsync(int[] vendorIds) {
            return base.Channel.GetDealersAsync(vendorIds);
        }
    }
}
